export const newFake = [
    {
        id: 1,
        label: 'Total Earnings',
        badge: 'ri-arrow-right-up-line',
        badgeClass: 'success',
        percentage: '+16.24',
        counter: '559.25',
        link: 'View net earnings',
        bgcolor: 'success',
        icon: 'bx bx-dollar-circle',
        decimals: 2,
        prefix: '$',
        suffix: 'k',
    },
    {
        id: 2,
        label: 'Orders',
        badge: 'ri-arrow-right-down-line',
        badgeClass: 'danger',
        percentage: '-3.57',
        counter: '36894',
        link: 'View all orders',
        bgcolor: 'info',
        icon: 'bx bx-shopping-bag',
        decimals: 0,
        prefix: '',
        separator: ',',
        suffix: '',
    },
    {
        id: 3,
        label: 'Customers',
        badge: 'ri-arrow-right-up-line',
        badgeClass: 'success',
        percentage: '+29.08',
        counter: '183.35',
        link: 'See details',
        bgcolor: 'warning',
        icon: 'bx bx-user-circle',
        decimals: 2,
        prefix: '',
        suffix: 'M',
    },
    {
        id: 4,
        label: 'My Balance',
        badgeClass: 'muted',
        percentage: '+0.00',
        counter: '165.89',
        link: 'Withdraw money',
        bgcolor: 'primary',
        icon: 'bx bx-wallet',
        decimals: 2,
        prefix: '$',
        suffix: 'k',
    },
    {
        id: 4,
        label: 'My Balance',
        badgeClass: 'muted',
        percentage: '+0.00',
        counter: '165.89',
        link: 'Withdraw money',
        bgcolor: 'primary',
        icon: 'bx bx-wallet',
        decimals: 2,
        prefix: '$',
        suffix: 'k',
    },
    {
        id: 4,
        label: 'My Balance',
        badgeClass: 'muted',
        percentage: '+0.00',
        counter: '165.89',
        link: 'Withdraw money',
        bgcolor: 'primary',
        icon: 'bx bx-wallet',
        decimals: 2,
        prefix: '$',
        suffix: 'k',
    },
    {
        id: 4,
        label: 'My Balance',
        badgeClass: 'muted',
        percentage: '+0.00',
        counter: '165.89',
        link: 'Withdraw money',
        bgcolor: 'primary',
        icon: 'bx bx-wallet',
        decimals: 2,
        prefix: '$',
        suffix: 'k',
    },
];
